### ISSUE TITLE
Get error when run 'make run': No module named 'fxa'

### ISSUE THREAD

**Issue by JadeVane** [mozilla-services/syncstorage-rs#1226]
I got the error above when i was running `make run`.

The full log here:

```
RUST_LOG=debug RUST_BACKTRACE=full cargo run --features tokenserver_test_mode -- --config config/local.toml
    Finished dev [unoptimized + debuginfo] target(s) in 3.12s
     Running `target/debug/syncstorage --config config/local.toml`
thread 'main' panicked at 'failed to create Tokenserver OAuth verifier: ApiError { kind: Internal("ModuleNotFoundError: No module named 'fxa'"), backtrace:    0: <syncstorage::error::ApiError as core::convert::From<syncstorage::error::ApiErrorKind>>::from
             at src/error.rs:252:24
   1: <T as core::convert::Into<U>>::into
             at /build/rustc-pMmQ1I/rustc-1.53.0+dfsg1+llvm/library/core/src/convert/mod.rs:538:9
   2: syncstorage::tokenserver::support::pyerr_to_actix_error
             at src/tokenserver/support.rs:232:31
   3: core::ops::function::FnOnce::call_once
             at /build/rustc-pMmQ1I/rustc-1.53.0+dfsg1+llvm/library/core/src/ops/function.rs:227:5
   ...
stack backtrace:
   0:     0x5597849925ac - std::backtrace_rs::backtrace::libunwind::trace::h667de636fd16ec22
                               at /build/rustc-pMmQ1I/rustc-1.53.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5597849925ac - std::backtrace_rs::backtrace::trace_unsynchronized::hb6272615657d5744
                               at /build/rustc-pMmQ1I/rustc-1.53.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5597849925ac - std::sys_common::backtrace::_print_fmt::h85b0a9a3797c535d
                               at /build/rustc-pMmQ1I/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5597849925ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h33e1fc29f9141885
                               at /build/rustc-pMmQ1I/rustc-1.53.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:46:22
   ...
Panic in Arbiter thread.
make: *** [Makefile:39：run] error 101
```

And the most important thing here, thank you for your efforts, it's a great project, thank you for all you put into it, I love this project.

**Comment by JadeVane** [comment]
It works, thank you!

**Comment by ethowitz** [comment]
Reopening this to track work on updating the makefile
