### ISSUE TITLE
`secret` is missing from this call

### ISSUE THREAD

**Issue by cvalaas** [mozilla-services/syncstorage-rs#1548]
https://github.com/mozilla-services/syncstorage-rs/blob/e9fde3e2b7c2aa8d8fd9030ab068f6c07f60f908/tools/tokenserver/purge_old_records.py#L331

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4247)

**Comment by cvalaas** [comment]
```Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/tools/tokenserver/purge_old_records.py", line 359, in <module>
    util.run_script(main)
  File "/app/tools/tokenserver/util.py", line 20, in run_script
    exitcode = main()
  File "/app/tools/tokenserver/purge_old_records.py", line 345, in main
    purge_old_records(
TypeError: purge_old_records() missing 1 required positional argument: 'secret'```
