### ISSUE TITLE
Build: failed to run custom build command for `openssl v0.9.24`

### ISSUE THREAD

**Issue by lyuyuan92** [mozilla-services/syncstorage-rs#163]
I have installed `libssl-dev` 1.1.1b-1ubuntu2.1 amd64.

When I build with `RUST_BACKTRACE=1 cargo build`, it returns the errors below:
```
error: failed to run custom build command for `openssl v0.9.24`
process didn't exit successfully: `/home/ylyu/Projects/syncstorage-rs/target/debug/build/openssl-7d464e70a21ffa53/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/ylyu/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::begin_panic
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:408
   6: build_script_build::main
             at ./build.rs:16
   7: std::rt::lang_start::{{closure}}
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
   8: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
   9: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  10: std::rt::lang_start_internal
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  11: std::rt::lang_start
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/rt.rs:64
  12: main
  13: __libc_start_main
  14: _start

warning: build failed, waiting for other jobs to finish...
error: build failed
```

The panic should've happened somewhere like [this line](https://github.com/sfackler/rust-openssl/blob/0.9.x/openssl/build.rs#L16).

If I remove the `Cargo.lock` file and rebuild, it builds fine.

**Comment by zoechi** [comment]
I'm still seeing this with 
```
cargo 1.40.0-nightly (5da4b4d47 2019-10-28)
```
```
nightly-x86_64-unknown-linux-gnu (default)
```

**Comment by kushwahashiv** [comment]
I am still getting this error in my mac with catelina
