### ISSUE TITLE
migrate_node.py script errors

### ISSUE THREAD

**Issue by erkolson** [mozilla-services/syncstorage-rs#571]
Attempted to migrate a node this morning and ran into a few errors.

1.  The script kicks off with lots of errors like this:
    ```
    ERROR:root:Skipping user <uid-redacted>: invalid literal for int() with base 10: 'NULL'
    ```
    The problem appears to be the [`int(keys_changed_at or generation)`](https://github.com/mozilla-services/syncstorage-rs/blob/user_migration3/tools/user_migration/migrate_node.py#L99) due to the csv parsing the `NULL` as a string literal.
    Across all BSOs in this server, this error occurred 4,794,880 times

2.  When it starts to process, it fails on the first transfer:
    ```
    INFO:root:Moving 2061 users
    INFO:root:Processing... <uid-redacted> -> ...
    ```
    With the error
    ```
    Traceback (most recent call last):
      File "user_migration/migrate_node.py", line 731, in <module>
        main()
      File "user_migration/migrate_node.py", line 724, in main
        databases, collections, bso_num, fxa_info, args, report)
      File "user_migration/migrate_node.py", line 571, in move_database
        report=report)
      File "user_migration/migrate_node.py", line 500, in move_user
        report.success(user.uid)
    AttributeError: 'Report' object has no attribute 'success'
    ```

**Comment by erkolson** [comment]
New error:
```
Traceback (most recent call last):
  File "user_migration/migrate_node.py", line 745, in <module>
    main()
  File "user_migration/migrate_node.py", line 738, in main
    databases, collections, bso_num, fxa_info, args, report)
  File "user_migration/migrate_node.py", line 585, in move_database
    report=report)
  File "user_migration/migrate_node.py", line 514, in move_user
    report.success(user.uid)
AttributeError: 'int' object has no attribute 'uid'
```

**Comment by erkolson** [comment]
All issues are resolved, thanks!
