### ISSUE TITLE
grpcio 0.6 breaks the spanner client's blocking calls

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#723]
grpcio 0.6 switched to std Future. Its blocking calls now appear to utilize the futures-executor crate, calling its [`block_on`](https://github.com/tikv/grpc-rs/commit/fd66ec789b2601cd88f015fa4a33a6b5da431c11#diff-31bbf71c54bca98a0ae3d40a327af940R40) method.

This results in errors under syncstorage-rs, ```panicked at 'cannot execute `LocalPool` executor from within another executor: EnterError'```.

This seems to only affect the unit tests (`cargo test`) implicit transactions (`begin()` called from `SpannerDb::get_transaction()`)

```
    Finished test [unoptimized + debuginfo] target(s) in 0.29s
     Running target/debug/deps/syncstorage-ca6e010b52e7ad74

running 1 test
thread 'db::tests::db::get_bsos_sort' panicked at 'cannot execute `LocalPool` executor from within another executor: EnterError', /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:78:18
stack backtrace:
   0:     0x55e909729fa4 - backtrace::backtrace::libunwind::trace::hc1c4a1d8ad423b97
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1:     0x55e909729fa4 - backtrace::backtrace::trace_unsynchronized::h82274781060cb056
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2:     0x55e909729fa4 - std::sys_common::backtrace::_print_fmt::h2a45d89b653a4da8
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x55e909729fa4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h41a0a93ab85e6aa1
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x55e90975765c - core::fmt::write::hdaea18585065a96d
                               at src/libcore/fmt/mod.rs:1069
   5:     0x55e909721953 - std::io::Write::write_fmt::h0cea70c809005252
                               at src/libstd/io/mod.rs:1504
   6:     0x55e90972c8c5 - std::sys_common::backtrace::_print::hd95f9978cc145ca4
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x55e90972c8c5 - std::sys_common::backtrace::print::hfb25ca2291be47d0
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x55e90972c8c5 - std::panicking::default_hook::{{closure}}::h44f76cee5dc8591c
                               at src/libstd/panicking.rs:198
   9:     0x55e90972c602 - std::panicking::default_hook::h198e1a712910f1e6
                               at src/libstd/panicking.rs:218
  10:     0x55e90972cf22 - std::panicking::rust_panic_with_hook::hc0b4730bb8013f9d
                               at src/libstd/panicking.rs:511
  11:     0x55e90972cb0b - rust_begin_unwind
                               at src/libstd/panicking.rs:419
  12:     0x55e909755451 - core::panicking::panic_fmt::h1ac71ad045d55416
                               at src/libcore/panicking.rs:111
  13:     0x55e909755273 - core::option::expect_none_failed::hb40004d71d61b685
                               at src/libcore/option.rs:1268
  14:     0x55e9094b79ba - core::result::Result<T,E>::expect::h61e156c6b751874f
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:963
  15:     0x55e9089f7142 - futures_executor::local_pool::run_executor::ha94fe7f02546bc98
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:78
  16:     0x55e9089f7709 - futures_executor::local_pool::block_on::he577184a4af6b224
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:317
  17:     0x55e9089df4a3 - grpcio::client::Client::unary_call::h45c2081076745bc6
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-0.6.0/src/client.rs:40
  18:     0x55e90890b026 - googleapis_raw::spanner::v1::spanner_grpc::SpannerClient::begin_transaction_opt::h9cc8f8c55b929ff5
                               at vendor/mozilla-rust-sdk/googleapis-raw/src/spanner/v1/spanner_grpc.rs:237
  19:     0x55e90890b08c - googleapis_raw::spanner::v1::spanner_grpc::SpannerClient::begin_transaction::h4fd3cb93b8524f5a
                               at vendor/mozilla-rust-sdk/googleapis-raw/src/spanner/v1/spanner_grpc.rs:241
  20:     0x55e907f784b4 - syncstorage::db::spanner::models::SpannerDb::begin::h3dbf7837f46375fe
                               at src/db/spanner/models.rs:320
  21:     0x55e907f78b8a - syncstorage::db::spanner::models::SpannerDb::get_transaction::h34ec89a8c0577c21
                               at src/db/spanner/models.rs:353
  22:     0x55e907f78fa4 - syncstorage::db::spanner::models::SpannerDb::sql_request::heb7b77c638d6dd52
                               at src/db/spanner/models.rs:371
  23:     0x55e907f796ec - syncstorage::db::spanner::models::SpannerDb::sql::h53ca86d37a90d4f7
                               at src/db/spanner/models.rs:384
  24:     0x55e907e4f5c6 - syncstorage::db::spanner::models::SpannerDb::touch_collection_async::{{closure}}::hefe6ac8166cb50be
                               at src/db/spanner/models.rs:914
  25:     0x55e907f3df92 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::he639980f95799827
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:66
  26:     0x55e907e60748 - syncstorage::db::spanner::models::SpannerDb::put_bso_async_test::{{closure}}::hf3ae4290cd07574f
                               at src/db/spanner/models.rs:1425
  27:     0x55e907f3efc2 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hf5d0be150d2fe2ca
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:66
  28:     0x55e907f32baa - <F as futures_core::future::TryFuture>::try_poll::hf747ed7ac523e04a
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.5/src/future.rs:83
  29:     0x55e907caa631 - <futures_util::future::try_future::into_future::IntoFuture<Fut> as core::future::future::Future>::poll::h6e5ec20285e4df7e
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/try_future/into_future.rs:31
  30:     0x55e908114f62 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::h90e13526eece7e0b
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/future/future/map.rs:67
  31:     0x55e9080bb471 - <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h93e4084b7aed1bd7
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  32:     0x55e907de0881 - <futures_util::future::try_future::MapErr<Fut,F> as core::future::future::Future>::poll::h9b975cf5b7b204dc
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.5/src/lib.rs:107
  33:     0x55e907e6d8c4 - <syncstorage::db::spanner::models::SpannerDb as syncstorage::db::Db>::put_bso::{{closure}}::h2add7dc5b1fee1e1
                               at src/db/spanner/models.rs:1768
  34:     0x55e907f33732 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h075eaff5282ffda0
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:66
  35:     0x55e90802b96e - <core::pin::Pin<P> as core::future::future::Future>::poll::h99b239b97196356a
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/future.rs:118
  36:     0x55e907cc2294 - syncstorage::db::tests::db::_inner_get_bsos_sort::{{closure}}::h9e06c8e4fefe3d69
                               at src/db/tests/db.rs:323
  37:     0x55e907f3ae52 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9f2135f56a94c9de
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:66
  38:     0x55e908164b02 - futures_executor::local_pool::LocalPool::run_until::{{closure}}::h01b8471dd8fd3cde
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:177
  39:     0x55e908161a1f - futures_executor::local_pool::run_executor::{{closure}}::he97386c4d57f0959
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:87
  40:     0x55e907bed098 - std::thread::local::LocalKey<T>::try_with::hd04eb37c2a935e10
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  41:     0x55e907bdde91 - std::thread::local::LocalKey<T>::with::h680bf0415f98030c
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  42:     0x55e90815be79 - futures_executor::local_pool::run_executor::h3d65629253810ce9
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:83
  43:     0x55e9081638fc - futures_executor::local_pool::LocalPool::run_until::h794994084e507175
                               at /home/pjenvey/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.5/src/local_pool.rs:174
  44:     0x55e907ecd613 - syncstorage::db::tests::db::get_bsos_sort::h87bc58aaad1d339b
                               at src/db/tests/db.rs:307
  45:     0x55e907cc5a49 - syncstorage::db::tests::db::get_bsos_sort::{{closure}}::h7382413a655a4b4f
                               at src/db/tests/db.rs:307
  46:     0x55e907e7f29e - core::ops::function::FnOnce::call_once::he48f042ac41548fe
                               at /media/ext/pjenvey/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:232
  47:     0x55e908280956 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hc165f65f4331a55c
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  48:     0x55e908280956 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb89f1f769cad07ce
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:318
  49:     0x55e908280956 - std::panicking::try::do_call::h104f7f3dae5a1b29
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
  50:     0x55e908280956 - std::panicking::try::h0e20f01361cba753
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
  51:     0x55e908280956 - std::panic::catch_unwind::h0bd0c84b5f4cd121
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
  52:     0x55e908280956 - test::run_test_in_process::hf34c22adfeb6853d
                               at src/libtest/lib.rs:541
  53:     0x55e908280956 - test::run_test::run_test_inner::{{closure}}::h40d568b4c10a12f1
                               at src/libtest/lib.rs:450
  54:     0x55e908258976 - std::sys_common::backtrace::__rust_begin_short_backtrace::hffd9774ad3f2d778
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/sys_common/backtrace.rs:130
  55:     0x55e90825dd05 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h4594020476cf52d4
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/mod.rs:475
  56:     0x55e90825dd05 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9d0a6d45b73e29e4
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:318
  57:     0x55e90825dd05 - std::panicking::try::do_call::h902fd77b30bb3bb7
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:331
  58:     0x55e90825dd05 - std::panicking::try::hc17d3a628e65d49d
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panicking.rs:274
  59:     0x55e90825dd05 - std::panic::catch_unwind::h9c9d49cbb6b18017
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/panic.rs:394
  60:     0x55e90825dd05 - std::thread::Builder::spawn_unchecked::{{closure}}::h6a6f5a333fd631a2
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libstd/thread/mod.rs:474
  61:     0x55e90825dd05 - core::ops::function::FnOnce::call_once{{vtable.shim}}::ha6fb197e0ce57f73
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/libcore/ops/function.rs:232
  62:     0x55e909734aca - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h1f1fac7de7dd9691
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  63:     0x55e909734aca - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::ha031f48633a6af54
                               at /rustc/49cae55760da0a43428eba73abcb659bb70cf2e4/src/liballoc/boxed.rs:1008
  64:     0x55e909734aca - std::sys::unix::thread::Thread::new::thread_start::h241864caf436e182
                               at src/libstd/sys/unix/thread.rs:87
  65:     0x7fc52b3036db - start_thread
                               at /build/glibc-2ORdQG/glibc-2.27/nptl/pthread_create.c:463
  66:     0x7fc52ae14a3f - __clone
  67:                0x0 - <unknown>
test db::tests::db::get_bsos_sort ... FAILED

failures:

failures:
    db::tests::db::get_bsos_sort

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 91 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by Mcat12** [comment]
After some initial work to convert these tests to `#[tokio::test]`/`#[actix_rt::test]`, the tests slow down and never finish:
https://github.com/mozilla-services/syncstorage-rs/tree/fix/spanner-tests

**Comment by fzzzy** [comment]
We should remove all use of sync spanner apis, I think. Maybe it's just begin() called from SpannerDb::get_transaction() as phil says.

**Comment by fzzzy** [comment]
Perhaps the tests should be made to use explicit transactions.

**Comment by pjenvey** [comment]
taken care of in #692 & #729 by switching tests to tokio executor (`#[async_test]` -> `#[tokio::test]`).

I haven't been able to reproduce the test slow downs locally. Maybe it's due to mark running them in intellij?

**Comment by Mcat12** [comment]
The test slow-downs are not due to IntelliJ, I've reproduced the issue when manually running `cargo test`.

**Comment by pjenvey** [comment]
> Perhaps the tests should be made to use explicit transactions.

#581 pretty much covers this and I've renamed the issue to make that clearer
