### ISSUE TITLE
SYNC_ENABLE_QUOTA not tested on ci

### ISSUE THREAD

**Issue by pjenvey** [mozilla-services/syncstorage-rs#829]
We're invoking cargo test with `ENABLE_QUOTA` in ci by mistake (which is missing the `SYNC_` prefix).

There's a couple failures when enabled:

https://app.circleci.com/pipelines/github/mozilla-services/syncstorage-rs/2473/workflows/c7061ed5-325c-4844-bdb8-f3d171db785f/jobs/8874

```
failures:

---- db::tests::batch::quota_test_append_batch stdout ----
thread 'main' panicked at 'assertion failed: db.append_to_batch(ab(uid, coll, id2.clone(), bsos3)).await.is_err()', src/db/tests/batch.rs:241:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:214
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  12: std::panicking::begin_panic
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:456
  13: syncstorage::db::tests::batch::quota_test_append_batch::{{closure}}
             at src/db/tests/batch.rs:241
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  15: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  16: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  18: std::thread::local::LocalKey<T>::with
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  19: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  20: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  21: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  22: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  23: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  24: tokio::runtime::basic_scheduler::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  25: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123
  26: tokio::runtime::Runtime::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444
  27: tokio::runtime::context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  28: tokio::runtime::handle::Handle::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  29: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  30: syncstorage::db::tests::batch::quota_test_append_batch
             at src/db/tests/batch.rs:205
  31: syncstorage::db::tests::batch::quota_test_append_batch::{{closure}}
             at src/db/tests/batch.rs:205
  32: core::ops::function::FnOnce::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:233
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:318
  35: std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
  36: std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
  37: std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
  38: test::run_test_in_process
             at src/libtest/lib.rs:541
  39: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
  40: test::run_test::run_test_inner
             at src/libtest/lib.rs:475
  41: test::run_test
             at src/libtest/lib.rs:505
  42: test::run_tests
             at src/libtest/lib.rs:284
  43: test::console::run_tests_console
             at src/libtest/console.rs:280
  44: test::test_main
             at src/libtest/lib.rs:120
  45: test::test_main_static
             at src/libtest/lib.rs:139
  46: syncstorage::main
  47: std::rt::lang_start::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  48: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  49: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  50: std::panicking::try
             at src/libstd/panicking.rs:325
  51: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  52: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  53: std::rt::lang_start
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  54: main
  55: __libc_start_main
  56: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

---- db::tests::batch::quota_test_create_batch stdout ----
thread 'main' panicked at 'assertion failed: db.create_batch(cb(uid, coll, bsos2)).await.is_err()', src/db/tests/batch.rs:200:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/io/mod.rs:1537
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:176
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:214
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:526
  12: std::panicking::begin_panic
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:456
  13: syncstorage::db::tests::batch::quota_test_create_batch::{{closure}}
             at src/db/tests/batch.rs:200
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/future/mod.rs:78
  15: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  16: tokio::coop::with_budget::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:127
  17: std::thread::local::LocalKey<T>::try_with
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:263
  18: std::thread::local::LocalKey<T>::with
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/thread/local.rs:239
  19: tokio::coop::with_budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:120
  20: tokio::coop::budget
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/coop.rs:96
  21: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:131
  22: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  23: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/macros/scoped_tls.rs:63
  24: tokio::runtime::basic_scheduler::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:213
  25: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/basic_scheduler.rs:123
  26: tokio::runtime::Runtime::block_on::{{closure}}
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:444
  27: tokio::runtime::context::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/context.rs:72
  28: tokio::runtime::handle::Handle::enter
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/handle.rs:76
  29: tokio::runtime::Runtime::block_on
             at /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.22/src/runtime/mod.rs:441
  30: syncstorage::db::tests::batch::quota_test_create_batch
             at src/db/tests/batch.rs:168
  31: syncstorage::db::tests::batch::quota_test_create_batch::{{closure}}
             at src/db/tests/batch.rs:168
  32: core::ops::function::FnOnce::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libcore/ops/function.rs:233
  33: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/liballoc/boxed.rs:1081
  34: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:318
  35: std::panicking::try::do_call
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:348
  36: std::panicking::try
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panicking.rs:325
  37: std::panic::catch_unwind
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/panic.rs:394
  38: test::run_test_in_process
             at src/libtest/lib.rs:541
  39: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:450
  40: test::run_test::run_test_inner
             at src/libtest/lib.rs:475
  41: test::run_test
             at src/libtest/lib.rs:505
  42: test::run_tests
             at src/libtest/lib.rs:284
  43: test::console::run_tests_console
             at src/libtest/console.rs:280
  44: test::test_main
             at src/libtest/lib.rs:120
  45: test::test_main_static
             at src/libtest/lib.rs:139
  46: syncstorage::main
  47: std::rt::lang_start::{{closure}}
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  48: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  49: std::panicking::try::do_call
             at src/libstd/panicking.rs:348
  50: std::panicking::try
             at src/libstd/panicking.rs:325
  51: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  52: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  53: std::rt::lang_start
             at /rustc/04488afe34512aa4c33566eb16d8c912a3ae04f9/src/libstd/rt.rs:67
  54: main
  55: __libc_start_main
  56: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    db::tests::batch::quota_test_append_batch
    db::tests::batch::quota_test_create_batch

test result: FAILED. 95 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by pjenvey** [comment]
Reopening I think we lost the fix for this probably during a merge
